#!/bin/sh

#   [1] REPOS-PATH   (the path to this repository)
#   [2] TXN-NAME     (the name of the txn about to be committed)

REPOS="$1"
TXN="$2"

PROJECTS="JIRA|PROJ|NAMES"

pname=`echo "$REPOS" | sed -Ene 's~.*/([^/]+)$~\1~p'`
prefixes=`echo "$PROJECTS"|sed -e 's/\|/- ,/g' -e 's/$/-/'`
# Make sure that the log message contains some text.
SVNLOOK=/usr/local/bin/svnlook
issues=`$SVNLOOK log -t "$TXN" "$REPOS" | head -n 1 | sed -E -ne "s/^((($PROJECTS)-[0-9]+ )+).*/\1/p" | sed -Ee 's/ $//' | tr ' ' '\n'`
if ! $SVNLOOK log -t "$TXN" "$REPOS" | grep -q "."; then
    echo "[$pname] Please, supply a comment" >&2
    exit 1
fi
if ! $SVNLOOK log -t "$TXN" "$REPOS" | head -n 1 | grep -q -E "^($PROJECTS)-[0-9]+"; then
    echo "[$pname] Please, supply JIRA issue in comment in the beginning of the first line, valid issue prefix(es): $prefixes" >&2
    exit 1
fi
if ! $SVNLOOK log -t "$TXN" "$REPOS" | head -n 1 | grep -q -E "^((($PROJECTS)-[0-9]+ )+)....."; then
    echo "[$pname] Please, write a meaningful comment with at least 5 characters" >&2
    exit 1
fi
for i in $issues; do
    err=`/path/to/jira-api-issue.sh $i`
    if [ ! -z "$err" ]; then 
	echo "[$pname] $err" >&2
	exit 1
    fi
done

# All checks passed, so allow the commit.
exit 0
